<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="Options">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gui" eType="#//GuiOptions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" upperBound="-1" eType="#//PasswordFile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuiOptions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unlockFrame" eType="#//UnlockFrameOptions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnlockFrameOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterEntry" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkTitle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkUsername" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkPassword" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkEmail" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkLocation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkNote" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selectedPassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PasswordFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="needBackup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encodeId" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PasswordSafe">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newEReference1" upperBound="-1"
        eType="#//PassObjectView"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassObject">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Title"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Username"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassObjectView" eSuperTypes="#//PassObject">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="history" upperBound="-1"
        eType="#//PassObjectHistory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassObjectHistory" eSuperTypes="#//PassObject">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
